# Generated by Django 3.0.5 on 2021-02-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_level',
            name='bronze_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account_level',
            name='bronze_max',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account_level',
            name='bronze_min',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account_level',
            name='bronze_profit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='bronze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='trade_account',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='trade_platform',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
